import "../styles/globals.css"

import {Roboto} from 'next/font/google'
const roboto = Roboto({
  weight: ['400', '500', '600'],
  style: ['normal', 'italic'],
  subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
        <script src="https://kit.fontawesome.com/9fe0e47678.js" crossorigin="anonymous"></script>
      </body>
    </html>
  )
}
