import "../styles/globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <script src="https://kit.fontawesome.com/9fe0e47678.js" crossorigin="anonymous"></script>
      </body>
    </html>
  )
}
